services:
  - type: web
    name: notify-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: API_KEY
        generateValue: true
